Conditional chat id setting
idchlife/kanal-interfaces-telegram pull request #26
Opened 2023-04-11 14:49 UTC by notetell

2023-04-12 08:45 UTC, idchlife requested changes

2023-04-12 08:45 UTC, idchlife commented on Gemfile
Why we need this dependency here? It is already required in gemspec

2023-04-12 09:08 UTC, notetell commented on Gemfile
Removed it https://github.com/idchlife/kanal-interfaces-telegram/pull/26/commits/27c3dbe3e629fc1adae938e215fe8c618e6bc3c2

2023-04-13 12:14 UTC, idchlife approved these changes

2023-04-13 12:14 UTC, merged